# Generated by Django 6.0.2 on 2026-03-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fitnessclass",
            options={
                "verbose_name": "Fitness class",
                "verbose_name_plural": "Fitness classes",
            },
        ),
    ]
