# Generated by Django 6.0.2 on 2026-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0002_alter_fitnessclass_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="instructor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="instructors/"),
        ),
    ]
