# Generated by Django 6.0.2 on 2026-06-01 15:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0003_instructor_email_instructor_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_user_class_booking",
        ),
        migrations.AlterField(
            model_name="classtype",
            name="default_capacity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="classtype",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="fitnessclass",
            name="capacity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user", "fitness_class"),
                name="unique_active_user_class_booking",
            ),
        ),
    ]
